AllCops:
  Exclude:
    - spec/spec_helper.rb

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Metrics/BlockLength:
  Enabled: false

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Documentation:
  Enabled: false